title = "DDob"
base_url = "/"

author = "DDob"
minify_html = true
compile_sass = false
build_search_index = true

ignored_content = ["**/cmake-build", "**/build*"]

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_referrer = true

[extra]
turbo_enabled = true
